"""empty message

Revision ID: 0cbeae1dac7f
Revises: 
Create Date: 2020-08-16 13:43:03.720179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cbeae1dac7f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('studentteacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('teacher_name', sa.String(length=20), nullable=False),
    sa.Column('session_image', sa.String(length=64), nullable=True),
    sa.Column('comments', sa.Text(), nullable=False),
    sa.Column('availability_of_materials', sa.Integer(), nullable=False),
    sa.Column('leadership', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_name'], ['teacher.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('studentteacher')
    op.drop_table('teacher')
    # ### end Alembic commands ###
